import { pgTable, text, timestamp, uuid, jsonb, boolean } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull(), emailVerified: boolean('email_verified').notNull().default(false), image: text('image'), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expires_at').notNull(), token: text('token').notNull(), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow(), ipAddress: text('ip_address'), userAgent: text('user_agent'), userId: text('user_id').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('account_id').notNull(), providerId: text('provider_id').notNull(), userId: text('user_id').notNull(), accessToken: text('access_token'), refreshToken: text('refresh_token'), idToken: text('id_token'), accessTokenExpiresAt: timestamp('access_token_expires_at'), refreshTokenExpiresAt: timestamp('refresh_token_expires_at'), scope: text('scope'), password: text('password'), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expires_at').notNull(), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow() })
export const qmsWorkspace = pgTable('qms_workspace', { id: uuid('id').defaultRandom().primaryKey(), name: text('name').notNull(), slug: text('slug').notNull(), createdAt: timestamp('created_at').notNull().defaultNow() })
export const qmsMembership = pgTable('qms_membership', { id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull(), userId: uuid('user_id').notNull(), role: text('role').notNull().default('editor'), createdAt: timestamp('created_at').notNull().defaultNow() })
export const qmsDocument = pgTable('qms_document', { id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull(), title: text('title').notNull(), code: text('code').notNull(), type: text('type').notNull(), status: text('status').notNull().default('draft'), content: text('content').notNull().default(''), createdBy: uuid('created_by').notNull(), updatedBy: uuid('updated_by').notNull(), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow() })
export const qmsAuditEvent = pgTable('qms_audit_event', { id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull(), userId: uuid('user_id').notNull(), action: text('action').notNull(), entityType: text('entity_type').notNull(), entityId: uuid('entity_id'), metadata: jsonb('metadata').notNull().default({}), createdAt: timestamp('created_at').notNull().defaultNow() })
export const qmsChatMessage = pgTable('qms_chat_message', { id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull(), userId: uuid('user_id').notNull(), conversationId: uuid('conversation_id').notNull(), role: text('role').notNull(), content: text('content').notNull(), createdAt: timestamp('created_at').notNull().defaultNow() })
