'use client'

import { useEffect, useMemo, useState } from 'react'
import { useChat } from '@ai-sdk/react'
import { DefaultChatTransport } from 'ai'
import { FileText, MessageSquare, Search, Send, Download, X, Bot, Plus, ChevronRight } from 'lucide-react'

type Doc = { path: string; name: string; code: string }

export default function Page() {
  const [docs, setDocs] = useState<Doc[]>([])
  const [query, setQuery] = useState('')
  const [selected, setSelected] = useState<Doc | null>(null)
  const [chatOpen, setChatOpen] = useState(true)
  const [input, setInput] = useState('')
  const { messages, sendMessage, status } = useChat({ transport: new DefaultChatTransport({ api: '/api/chat' }) })

  useEffect(() => { fetch('/qms-manifest.json').then((r) => r.json()).then(setDocs).catch(() => setDocs([])) }, [])
  const filtered = useMemo(() => docs.filter((doc) => `${doc.name} ${doc.code}`.toLowerCase().includes(query.toLowerCase())), [docs, query])
  const submit = () => { const text = input.trim(); if (!text || status === 'streaming') return; setInput(''); sendMessage({ text }) }

  return <div className="min-h-screen bg-[#f5f6f8] text-[#20242a] dark:bg-[#121416] dark:text-[#f4f6f8]">
    <header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-[#dfe3e8] bg-white/95 px-5 backdrop-blur dark:border-[#2a2e33] dark:bg-[#191c20]/95">
      <div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center bg-[#e21b2d] text-sm font-black text-white">ID</div><div><div className="text-sm font-bold">IDSS-QMS</div><div className="text-[10px] uppercase tracking-[.16em] text-[#89919a]">Quality system</div></div><ChevronRight size={15} className="text-[#a0a7af]" /><span className="text-sm font-semibold">Document library</span></div>
      <button onClick={() => setChatOpen(!chatOpen)} className="inline-flex items-center gap-2 border border-[#dfe3e8] px-3 py-2 text-xs font-bold hover:border-[#e21b2d] dark:border-[#343a41]" aria-label="Toggle AI assistant"><MessageSquare size={15} /> AI assistant</button>
    </header>
    <main className="mx-auto grid max-w-[1600px] gap-5 p-5 lg:grid-cols-[minmax(0,1fr)_390px] lg:p-8">
      <section className="min-w-0"><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-2 text-[11px] font-bold uppercase tracking-[.15em] text-[#e21b2d]">Controlled information · 56 imported files</div><h1 className="text-3xl font-bold tracking-[-.04em]">Document library</h1><p className="mt-1 text-sm text-[#747d87]">All documents from the supplied ISO 9001:2015 archive.</p></div><button onClick={() => setChatOpen(true)} className="inline-flex items-center justify-center gap-2 bg-[#e21b2d] px-4 py-2.5 text-xs font-bold text-white"><Plus size={15} /> Create with AI</button></div>
        <div className="mb-4 flex items-center gap-2 border border-[#dfe3e8] bg-white px-3 dark:border-[#343a41] dark:bg-[#191c20]"><Search size={15} className="text-[#89919a]" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search by filename or QP code..." className="h-11 w-full bg-transparent text-sm outline-none" /></div>
        <div className="overflow-hidden border border-[#dfe3e8] bg-white dark:border-[#2a2e33] dark:bg-[#191c20]"><div className="flex items-center justify-between border-b border-[#edf0f2] px-5 py-4 dark:border-[#2a2e33]"><div><h2 className="text-sm font-bold">Master document list</h2><p className="mt-1 text-xs text-[#89919a]">{filtered.length} documents available</p></div><span className="bg-[#e8f8f7] px-2 py-1 text-[10px] font-bold text-[#087f78]">ARCHIVE LOADED</span></div><div className="divide-y divide-[#edf0f2] dark:divide-[#2a2e33]">{filtered.map((doc) => <button key={doc.path} onClick={() => setSelected(doc)} className="flex w-full items-center gap-3 px-5 py-3 text-left hover:bg-[#fafbfc] dark:hover:bg-[#22262b]"><FileText size={17} className="shrink-0 text-[#e21b2d]" /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{doc.name}</span><span className="text-[11px] text-[#89919a]">{doc.code} · Controlled source document</span></span><Download size={15} className="shrink-0 text-[#9aa1a9]" /></button>)}{!filtered.length && <div className="p-10 text-center text-sm text-[#89919a]">No documents match this search.</div>}</div></div>
      </section>
      {chatOpen && <aside className="flex min-h-[620px] flex-col border border-[#dfe3e8] bg-white dark:border-[#2a2e33] dark:bg-[#191c20]"><div className="flex items-center justify-between border-b border-[#edf0f2] p-4 dark:border-[#2a2e33]"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#e8f8f7] text-[#087f78]"><Bot size={18} /></div><div><h2 className="text-sm font-bold">QMS AI assistant</h2><p className="text-[11px] text-[#89919a]">Continuous conversation · ISO 9001</p></div></div><button onClick={() => setChatOpen(false)} className="p-1 text-[#89919a]" aria-label="Close assistant"><X size={16} /></button></div><div className="flex-1 space-y-4 overflow-y-auto p-4">{messages.length === 0 && <div className="border-l-2 border-[#e21b2d] bg-[#fff6f7] p-4 text-xs leading-5 text-[#5f6872] dark:bg-[#321b1f] dark:text-[#d8b7bb]"><strong className="mb-1 block text-[#c91829]">Spreman za rad</strong>Traži novi dokument, reviziju procedure ili formatiranje prema QP strukturi. Kontekst razgovora ostaje aktivan.</div>}{messages.map((message) => <div key={message.id} className={message.role === 'user' ? 'ml-8 rounded-lg bg-[#eef3f7] p-3 text-xs leading-5 dark:bg-[#29323a]' : 'mr-4 rounded-lg border border-[#edf0f2] p-3 text-xs leading-5 dark:border-[#343a41]'}><div className="mb-1 text-[10px] font-bold uppercase tracking-wide text-[#89919a]">{message.role === 'user' ? 'Ti' : 'QMS AI'}</div>{message.parts.map((part, index) => part.type === 'text' ? <p key={index} className="whitespace-pre-wrap">{part.text}</p> : null)}</div>)}</div><div className="border-t border-[#edf0f2] p-3 dark:border-[#2a2e33]"><textarea value={input} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing && e.keyCode !== 229) { e.preventDefault(); submit() } }} placeholder="Napiši zahtjev za novi dokument..." className="mb-2 h-20 w-full resize-none bg-transparent p-2 text-xs outline-none" /><div className="flex items-center justify-between"><span className="text-[10px] text-[#89919a]">Enter šalje · Shift+Enter novi red</span><button onClick={submit} disabled={!input.trim() || status === 'streaming'} className="flex h-9 w-9 items-center justify-center bg-[#e21b2d] text-white disabled:opacity-40" aria-label="Send message"><Send size={15} /></button></div></div></aside>}
    </main>
    {selected && <div className="fixed inset-0 z-30 flex items-center justify-center bg-[#101317]/40 p-4"><div className="w-full max-w-lg border border-[#dfe3e8] bg-white p-6 shadow-2xl dark:border-[#343a41] dark:bg-[#191c20]"><div className="flex items-start justify-between"><div><div className="mb-2 text-[10px] font-bold uppercase tracking-wide text-[#e21b2d]">{selected.code}</div><h2 className="text-lg font-bold">{selected.name}</h2><p className="mt-2 text-xs text-[#89919a]">Original archive file. Download or ask the AI assistant to use this document as a reference.</p></div><button onClick={() => setSelected(null)} aria-label="Close document"><X size={18} className="text-[#89919a]" /></button></div><a href={`/qms-documents/${selected.path}`} download className="mt-6 inline-flex items-center gap-2 bg-[#e21b2d] px-4 py-2.5 text-xs font-bold text-white"><Download size={15} /> Download original</a></div></div>}
  </div>
}
